import type { AgentTask, ProjectArtifact } from "./types";

const t = (name: string, description: string) => ({ name, description });

export const AGENT_TASKS: AgentTask[] = [
  {
    id: "F-01", name: "选题规划 Agent", shortName: "选题规划", stage: "pre", priority: "P1", risk: "R1",
    description: "从临床问题出发，挖掘领域热点并形成差异化选题。",
    objective: "把模糊研究兴趣转化为 Research Brief、PICOS 草案和选题方案。",
    tools: [t("get_field_hotspot", "抓取领域热点与临床空白"), t("build_picos_frame", "构建 PICOS 草案"), t("query_dataset_inventory", "查询可用数据摘要"), t("calculate_innovation_score", "评估创新与可行性"), t("generate_topic_plan", "生成多套选题方案")],
    steps: ["收集疾病、偏好、目标期刊和数据条件", "并行获取热点与构建 PICOS", "展示热点和 PICOS 草案", "用户确认方向", "生成选题方案和评分"],
    gate: "研究方向和 PICOS 会影响后续全流程，需 R1 确认。",
    inputs: ["疾病/领域", "研究偏好", "目标期刊层级", "既往数据情况"],
    outputs: ["Research Brief", "PICOS 草案", "创新可行性评分", "三套选题方案"],
    exceptions: ["领域缺失时主动追问", "证据不足时标记 PARTIAL", "PICOS 冲突时先修正"],
    next: ["F-02 文献综述", "F-03 研究设计"],
    prompt: "我想做肺癌真实世界预后研究，手里有 500 例院内数据。",
  },
  {
    id: "F-02", name: "文献综述 Agent", shortName: "文献综述", stage: "pre", priority: "P1", risk: "R1",
    description: "完成综述协议、多库检索、筛选、证据提取、质量评价和综述写作。",
    objective: "形成可审计的 Review Package，而不是直接从题录生成流畅文本。",
    tools: [t("define_review_protocol", "定义综述协议"), t("build_database_search_strategy", "生成检索式"), t("search_literature_databases", "执行多库检索"), t("screen_literature_records", "筛选文献"), t("extract_study_evidence", "提取证据"), t("assess_risk_of_bias", "评价偏倚风险"), t("compose_literature_review", "撰写综述")],
    steps: ["定义 Review Protocol", "确认检索策略", "检索、导入和去重", "筛选与 PRISMA", "提取证据并评价质量", "综合证据并撰写"],
    gate: "检索策略、纳入证据和正式导出需确认。",
    inputs: ["PICOS/主题", "综述类型", "数据库与年限", "已有题录或 PDF"],
    outputs: ["Review Protocol", "Search Log", "Evidence Set", "Synthesis Map", "Review Package"],
    exceptions: ["全文不可用时不推断正文", "PRISMA 不闭合时阻断导出"],
    next: ["F-03 研究设计", "F-08 报告生成"],
    prompt: "帮我查一下胃癌预后模型的研究现状和争议。",
  },
  {
    id: "F-03", name: "研究设计 Agent", shortName: "研究设计", stage: "pre", priority: "P1", risk: "R2",
    description: "完成研究设计、样本量、偏倚控制、CRF、访视表和 Protocol。",
    objective: "把临床问题转为可执行、可审计的 Study Design Package。",
    tools: [t("parse_clinical_research_question", "解析研究问题"), t("route_study_design", "路由研究设计"), t("validate_design_logic", "校验设计逻辑"), t("calculate_sample_size", "估算样本量"), t("generate_crf_schema", "生成 CRF"), t("compose_study_protocol", "生成方案")],
    steps: ["解析问题和 PICOS", "路由设计类型", "校验逻辑", "确认设计", "生成样本量、CRF、统计框架和 Protocol"],
    gate: "设计类型、样本量参数和正式 Protocol 属于 R2/R3 确认点。",
    inputs: ["研究问题/PICOS", "Evidence Set", "数据来源", "资源约束"],
    outputs: ["PICOS Profile", "Design Decision Record", "Sample Size Report", "CRF Schema", "Study Protocol"],
    exceptions: ["时间零点不清时阻断", "主要结局缺失时阻断"],
    next: ["F-11 伦理注册", "F-12 研究执行管理", "F-04 数据清洗", "F-05 算法推荐"],
    prompt: "这个胃癌预后研究该设计成队列还是病例对照？",
  },
  {
    id: "F-04", name: "数据清洗 Agent", shortName: "数据清洗", stage: "mid", priority: "P0", risk: "R2",
    description: "识别数据质量问题，确认后生成可审计的新数据版本。",
    objective: "在不覆盖原始数据的前提下得到适合分析的 Dataset Version。",
    tools: [t("inspect_dataset_schema", "读取字段和单位"), t("profile_data_quality", "统计缺失和异常"), t("detect_data_issues", "检查逻辑冲突"), t("recommend_cleaning_plan", "提出清洗计划"), t("preview_cleaning_impact", "预览影响"), t("execute_cleaning_plan", "生成新版本")],
    steps: ["确认授权和数据字典", "数据画像", "生成 Cleaning Plan", "预览影响", "确认规则", "执行并复核新版本"],
    gate: "应用清洗属于数据变更，必须 R2 确认。",
    inputs: ["Dataset", "数据字典", "Study Protocol"],
    outputs: ["Data Quality Report", "Cleaning Plan", "Dataset Version", "Cleaning Log"],
    exceptions: ["单位不明时阻断", "样本量明显下降时二次确认"],
    next: ["F-05 算法推荐", "F-06 统计分析"],
    prompt: "我有一个 Excel，帮我检查缺失、异常值和日期逻辑。",
  },
  {
    id: "F-05", name: "算法推荐 Agent", shortName: "算法推荐", stage: "mid", priority: "P0", risk: "R2",
    description: "根据设计、目标和数据画像选择统计方法并生成 Analysis Plan。",
    objective: "把研究意图转为变量、方法和参数明确的 Analysis Plan。",
    tools: [t("profile_dataset", "生成数据画像"), t("query_algorithm_registry", "查询算法注册表"), t("filter_method_constraints", "过滤不适用方法"), t("evaluate_method_fit", "评估适配度"), t("generate_analysis_plan", "生成分析计划")],
    steps: ["读取设计和目标", "生成数据画像", "方法约束过滤", "展示推荐和排除原因", "确认方法与变量", "保存 Analysis Plan"],
    gate: "方法、变量和参数确认后才能进入执行。",
    inputs: ["PICOS", "Study Protocol", "Dataset Version", "分析目标"],
    outputs: ["方法推荐卡", "排除清单", "Analysis Plan"],
    exceptions: ["无方法满足约束时停止", "未实现方法明确标记"],
    next: ["F-06 统计分析"],
    prompt: "这个生存结局该用 Cox 还是 Logistic？",
  },
  {
    id: "F-06", name: "统计分析 Agent", shortName: "统计分析", stage: "mid", priority: "P1", risk: "R2",
    description: "校验分析计划、审计环境与代码、执行模型并注册 Verified Result。",
    objective: "创建可复现 Analysis Run 和 Verified Result。",
    tools: [t("validate_analysis_plan", "校验分析计划"), t("validate_statistical_environment", "检查统计环境"), t("audit_analysis_script", "审计分析脚本"), t("execute_statistical_model", "执行模型"), t("validate_result_bundle", "验证结果包"), t("package_analysis_code", "打包可复现代码")],
    steps: ["固定计划和数据版本", "检查环境与脚本", "确认执行参数", "执行模型", "验证结果", "生成可复现包"],
    gate: "启动分析、模型调整和正式结果登记均需 R2 确认。",
    inputs: ["Approved Analysis Plan", "Dataset Version", "Algorithm Version"],
    outputs: ["Analysis Run", "Environment Report", "Script Audit", "Verified Result", "Code Package"],
    exceptions: ["模型不收敛时保留失败运行", "结果校验失败不登记 Verified Result"],
    next: ["F-07 统计绘图", "F-08 报告生成"],
    prompt: "按已批准的 Cox 分析计划运行，并检查环境和代码可复现性。",
  },
  {
    id: "F-07", name: "统计绘图 Agent", shortName: "统计绘图", stage: "mid", priority: "P0", risk: "R3",
    description: "将 Verified Result 转为发表级科研图表和可复现绘图代码。",
    objective: "生成绑定 Result ID 的 Figure Asset。",
    tools: [t("recommend_plot_spec", "推荐图形"), t("load_journal_plot_style", "加载期刊样式"), t("generate_plot_code", "生成绘图代码"), t("render_scientific_figure", "渲染图形"), t("export_figure_bundle", "导出图包")],
    steps: ["选择 Verified Result", "推荐图形", "确认视觉编码", "生成代码并渲染", "导出图包"],
    gate: "最终图表导出属于 R3。",
    inputs: ["Verified Result", "目标期刊", "表达目标"],
    outputs: ["Figure Asset", "SVG/PDF/PNG", "绘图代码", "图注"],
    exceptions: ["无 Verified Result 时阻断", "拒绝隐藏不利数据"],
    next: ["F-08 报告生成"],
    prompt: "把生存结果画成 KM 曲线，并导出期刊图件。",
  },
  {
    id: "F-08", name: "报告生成 Agent", shortName: "报告生成", stage: "post", priority: "P0", risk: "R3",
    description: "生成论文、投稿文书、声明材料、审稿回复和合规检查。",
    objective: "形成统计数值和引用 100% 可追溯的 Manuscript Version。",
    tools: [t("collect_verified_artifacts", "汇集项目资产"), t("draft_imrad_section", "撰写 IMRAD"), t("generate_statistical_tables", "生成统计表"), t("draft_cover_letter", "生成 Cover Letter"), t("build_response_letter_matrix", "生成审稿回复矩阵"), t("check_manuscript_compliance", "合规检查")],
    steps: ["收集资产", "规划稿件结构", "逐章生成", "生成表格和声明", "处理审稿意见", "溯源与合规检查", "确认后导出"],
    gate: "正式稿、投稿文书和回复信导出属于 R3。",
    inputs: ["Protocol", "Evidence Set", "Verified Result", "Figure Asset", "目标期刊"],
    outputs: ["Manuscript", "Cover Letter", "Statements", "Response Letter", "Compliance Report"],
    exceptions: ["无 Verified Result 不写正式 Results 数值", "无事实依据不生成伦理/作者声明"],
    next: ["F-09 文献格式化", "F-10 期刊推荐"],
    prompt: "基于已验证结果写 Results 和 Discussion，并准备 Cover Letter。",
  },
  {
    id: "F-09", name: "文献格式化 Agent", shortName: "文献格式化", stage: "post", priority: "P2", risk: "R3",
    description: "解析题录、处理冲突与缺失，输出目标期刊格式。",
    objective: "生成来源明确、冲突已确认的 Reference Set。",
    tools: [t("import_reference_set", "导入题录"), t("resolve_reference_metadata", "补充元数据"), t("disambiguate_author", "作者消歧"), t("format_reference_set", "格式化引用"), t("validate_reference_set", "校验引用集")],
    steps: ["导入题录", "解析元数据", "确认冲突", "格式转换", "检查正文对应", "保存版本"],
    gate: "冲突元数据和正式引用导出需确认。",
    inputs: ["Reference Set", "Manuscript", "目标期刊"],
    outputs: ["格式化引用", "Reference Set", "冲突报告"],
    exceptions: ["元数据不足时保留缺失", "多来源冲突等待选择"],
    next: ["F-10 期刊推荐", "返回 F-08 导出"],
    prompt: "把参考文献转成目标期刊格式，并列出缺失 DOI。",
  },
  {
    id: "F-10", name: "期刊推荐 Agent", shortName: "期刊推荐", stage: "post", priority: "P2", risk: "R3",
    description: "完成选刊、投稿包检查、决定信解析、改投和接收后清单。",
    objective: "给出可解释、带来源日期且不承诺录用的投稿方案。",
    tools: [t("extract_manuscript_profile", "提取稿件画像"), t("query_journal_database", "检索期刊规则"), t("rank_journal_fit", "期刊匹配排序"), t("build_submission_checklist", "生成投稿清单"), t("validate_submission_package", "检查投稿包"), t("build_post_acceptance_checklist", "生成接收后清单")],
    steps: ["读取稿件和偏好", "形成约束", "检索期刊", "生成梯队", "检查投稿包", "处理拒稿/接收后流程"],
    gate: "投稿包导出、外部提交、支付、版权签署属于 R3。",
    inputs: ["Manuscript", "文章类型", "期刊偏好", "决定信/接收通知"],
    outputs: ["Journal Candidates", "Submission Plan", "Submission Package Report", "Post-acceptance Checklist"],
    exceptions: ["动态信息无法验证时阻断正式推荐", "不承诺录用概率"],
    next: ["返回 F-08/F-09 修改稿件"],
    prompt: "帮我推荐适合的肿瘤学期刊，并检查投稿包是否齐全。",
  },
  {
    id: "F-11", name: "伦理注册 Agent", shortName: "伦理注册", stage: "pre", priority: "P1", risk: "R2",
    description: "准备伦理审查、知情同意、隐私治理和临床注册材料。",
    objective: "把 Study Protocol 转换为伦理递交和注册字段草案。",
    tools: [t("classify_ethics_review_type", "判断伦理审查类型"), t("generate_ethics_submission_checklist", "生成材料清单"), t("draft_informed_consent", "起草知情同意"), t("validate_privacy_deidentification_plan", "检查隐私脱敏"), t("prepare_trial_registration_fields", "生成注册字段"), t("check_registration_consistency", "检查注册一致性")],
    steps: ["读取 Protocol", "判断审查类型", "生成材料清单", "准备知情同意/豁免理由", "生成注册字段", "一致性检查"],
    gate: "伦理路径、知情同意和注册字段需 R2 确认；外部提交属于 R3。",
    inputs: ["Study Protocol", "数据授权信息", "伦理要求", "注册需求"],
    outputs: ["Ethics Package", "Consent Draft", "Privacy Plan", "Registration Draft"],
    exceptions: ["不得声称已获伦理批准", "缺少 Protocol 时返回 F-03"],
    next: ["F-12 研究执行管理", "F-04 数据清洗"],
    prompt: "帮我准备回顾性研究的伦理材料和注册字段草案。",
  },
  {
    id: "F-12", name: "研究执行管理 Agent", shortName: "研究执行", stage: "mid", priority: "P1", risk: "R2",
    description: "管理招募、入组、随访、方案偏离、CRF质控和监查报告。",
    objective: "把 Protocol 转换为可追踪的研究执行管理方案。",
    tools: [t("build_recruitment_plan", "生成招募计划"), t("track_recruitment_funnel", "追踪招募漏斗"), t("generate_followup_schedule", "生成随访计划"), t("audit_followup_deviation", "审计随访偏离"), t("build_site_qc_plan", "生成站点质控计划"), t("generate_monitoring_report", "生成监查报告")],
    steps: ["读取 Protocol 和伦理路径", "生成招募计划", "建立随访窗口", "追踪入组与失访", "审计 CRF 和方案偏离", "生成监查报告"],
    gate: "影响受试者、站点流程或数据解释的动作需 R2 确认。",
    inputs: ["Executable Protocol", "伦理路径", "站点信息", "CRF/EDC 字段"],
    outputs: ["Recruitment Plan", "Screening Log", "Follow-up Schedule", "Deviation Log", "Monitoring Report"],
    exceptions: ["不得自动联系患者", "设计变化返回 F-03", "严重偏离需人工升级"],
    next: ["F-04 数据清洗", "F-06 统计分析"],
    prompt: "帮我规划患者招募、随访窗口和 CRF 质控。",
  },
];

export const PROJECT_ARTIFACTS: ProjectArtifact[] = [
  { id: "brief_001", type: "Research Brief", name: "免疫治疗真实世界预后研究", version: "v3", status: "已确认", updatedAt: "今天 09:42", source: "F-01 选题规划" },
  { id: "protocol_014", type: "Study Protocol", name: "NSCLC 预后队列研究方案", version: "v2", status: "已确认", updatedAt: "今天 10:18", source: "F-03 研究设计" },
  { id: "ethics_002", type: "Ethics Package", name: "回顾性研究伦理材料包", version: "v1", status: "待确认", updatedAt: "今天 10:45", source: "F-11 伦理注册" },
  { id: "exec_003", type: "Monitoring Report", name: "随访与CRF质控监查报告", version: "v1", status: "草稿", updatedAt: "今天 10:58", source: "F-12 研究执行管理" },
  { id: "data_004", type: "Dataset Version", name: "NSCLC_clean_2026Q2", version: "v4", status: "已验证", updatedAt: "今天 11:06", source: "F-04 数据清洗" },
  { id: "plan_008", type: "Analysis Plan", name: "Cox 主分析 + IPTW 敏感性分析", version: "v1", status: "已确认", updatedAt: "今天 11:35", source: "F-05 算法推荐" },
  { id: "run_456", type: "Verified Result", name: "Cox proportional hazards", version: "v1", status: "已验证", updatedAt: "今天 12:08", source: "F-06 统计分析" },
  { id: "fig_032", type: "Figure Asset", name: "Overall survival KM curve", version: "v2", status: "已验证", updatedAt: "今天 12:26", source: "F-07 统计绘图" },
  { id: "ms_006", type: "Manuscript", name: "IMRAD manuscript", version: "v6", status: "草稿", updatedAt: "今天 13:02", source: "F-08 报告生成" },
];

export const STAGE_META = {
  pre: { label: "前置科研规划", subtitle: "选题 · 文献 · 设计 · 伦理", color: "wine" },
  mid: { label: "中段执行分析", subtitle: "执行 · 数据 · 算法 · 统计 · 绘图", color: "teal" },
  post: { label: "后置发表交付", subtitle: "写作 · 引用 · 投稿 · 接收后", color: "gold" },
} as const;

